### ISSUE TITLE
module name loaded but not showing module attribute

### ISSUE THREAD

**Issue by jinoj** [phenomenes/ansible-snippets#1]
module name loaded but not showing module attribute.

**Comment by phenomenes** [comment]
@jinoj what module is not showing the attributes?
This is working on a fresh installation, please check the README for instructions on how to install it and make sure that no other vim plugins are interfering.

**Comment by jinoj** [comment]
Dear frd... Every thing working fine.. But module attributes not loaded..

For example I have use ec2. 
ec2:  - - -  tab enter autoloaded

But - - - attributes not loaded

Instance_type:
Count
Ami

If I make any mistake kindly help me.. Its useful for us

**Comment by phenomenes** [comment]
Could you please share step by step how are you installing the snippets and how are you using them?

**Comment by jinoj** [comment]
Ok... just few min i will update..

**Comment by jinoj** [comment]
vvim .vimrc 

Plugin 'phenomenes/ansible-snippets'

let g:ansible_unindent_after_newline = 1
let g:ansible_yamlKeyName = 'yamlKey'
let g:ansible_attribute_highlight = "ob"
let g:ansible_extra_keywords_highlight = 1
let g:ansible_normal_keywords_highlight = 'Constant'
let g:ansible_with_keywords_highlight = 'Constant'
let g:ansible_template_syntaxes = { '*.rb.j2': 'ruby' }
au BufRead,BufNewFile */playbooks/*.yml set filetype=yaml.ansible
let g:ansible_name_highlight = 'b'

**Comment by jinoj** [comment]
![image](https://user-images.githubusercontent.com/29822478/52565366-95e8a000-2e2c-11e9-84fd-b2340430c659.png)

**Comment by jinoj** [comment]
![image](https://user-images.githubusercontent.com/29822478/52565408-b153ab00-2e2c-11e9-8f34-ad1b5dd36efc.png)

**Comment by jinoj** [comment]
not loaded attributes

**Comment by jinoj** [comment]
i am using Vundle (Vim plugin manager.)

**Comment by jinoj** [comment]
if anything wrong kindly give vimrc file

**Comment by phenomenes** [comment]
try this, open a new file with vim:
```
vim new.yaml
```
Switch to _insert_ mode by pressing _i_
Type `ec2` and press tab.

**Comment by jinoj** [comment]
![image](https://user-images.githubusercontent.com/29822478/52567176-ab13fd80-2e31-11e9-806a-b162a0af4082.png)

**Comment by jinoj** [comment]
![image](https://user-images.githubusercontent.com/29822478/52567248-d7c81500-2e31-11e9-8a0b-4d5f0015f2b2.png)

**Comment by jinoj** [comment]
@phenomenes help me!!!!!!!!!!!!!

**Comment by phenomenes** [comment]
just type `ec2` and tab.

not this:
```
---
- ec2:
```

If still doesn't work, try removing all the _ansible_ lines from your vim configuration, some other plugins might be interfering.

**Comment by jinoj** [comment]
i tried but not reflecting me

**Comment by jinoj** [comment]
my vimrc

set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)

" ...

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required


Plugin 'tmhedberg/SimpylFold'
Plugin 'vim-scripts/indentpython.vim'
Bundle 'Valloric/YouCompleteMe'
Plugin 'vim-syntastic/syntastic'
Plugin 'nvie/vim-flake8'
Plugin 'phenomenes/ansible-snippets'
Plugin 'jnurmine/Zenburn'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}

set splitbelow
set splitright

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Enable folding
set foldmethod=indent
set foldlevel=99

" Enable folding with the spacebar
nnoremap <space> za

let g:SimpylFold_docstring_preview=1

highlight BadWhitespace ctermbg=red guibg=darkred
au BufNewFile,BufRead *.yaml; set tabstop=2 set softtabstop=2 set shiftwidth=2 set expandtab set autoindent set fileformat=unix
" au BufNewFile,BufRead *.py; set tabstop=4 set softtabstop=4 set shiftwidth=4 set textwidth=79 set expandtab set autoindent set fileformat=unix
" au BufNewFile,BufRead *.js,*.html,*.css; set tabstop=2 set softtabstop=2 set shiftwidth=2
" au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

set encoding=utf-8

let g:ycm_autoclose_preview_window_after_completion=1
let g:ycm_autoclose_preview_window_after_completion = 0
let g:ycm_server_python_interpreter = '/usr/bin/python'

py3 << EOF
import os
import sys
if 'VIRTUAL_ENV' in os.environ:
	project_base_dir = os.environ['VIRTUAL_ENV']
	activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
	exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'), dict(__file__=activate_this))
EOF

let python_highlight_all=1
syntax on

if has('gui_running')
    set background=dark
    colorscheme solarized
else
    colorscheme zenburn
endif

call togglebg#map("<F5>")

let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree

set nu

set clipboard=unnamed
map <C-n> :NERDTreeToggle<CR>
set tabstop=2 softtabstop=2
set cursorline
set cursorcolumn

**Comment by phenomenes** [comment]
you have the plugins defined in the wrong block, plugins need to be defined between the `vundle` blocks:
```
" minimal working configuration
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'phenomenes/ansible-snippets'
Plugin 'SirVer/ultisnips'

call vundle#end()

filetype plugin indent on
```

Pay attention to the comments in your configuration:
```
" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)

" ...

" All of your Plugins must be added before the following line
```
Also you need to install either UltiSnips or SnipMate, please read the README carefully again.

**Comment by jinoj** [comment]
thank u ji its working and helping me
