### ISSUE TITLE
Snippet regeneration

### ISSUE THREAD

**Issue by michaelfranzl** [phenomenes/ansible-snippets#2]
Thank you for these useful snippets!

https://github.com/phenomenes/ansible-snippets/blob/ceb5a528a36c41eb55cd58b79fe4954b94929c05/README.md?plain=1#L38-L39

There has not been any update to this repository in 3 years even though the `devel` branch of Ansible has evolved.

Could you publish the script(s) that generated the snippets so that they can be independently updated?

**Comment by z0mbix** [comment]
I believe these were generated using this repo:

https://github.com/phenomenes/ansible_snippet_generator
